// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz5CqwBsf1SiyNKznui9bsdxp5RQ7L-LE',
    appId: '1:567445844346:web:b34c16928b7c86c685e6c3',
    messagingSenderId: '567445844346',
    projectId: 'quran-app-9116d',
    authDomain: 'quran-app-9116d.firebaseapp.com',
    storageBucket: 'quran-app-9116d.firebasestorage.app',
    measurementId: 'G-KS58JN7732',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCafy385KAP0T4ydfd1j7CmkfsCfUXqSsE',
    appId: '1:567445844346:android:d40b21d13e6469a585e6c3',
    messagingSenderId: '567445844346',
    projectId: 'quran-app-9116d',
    storageBucket: 'quran-app-9116d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXGbIlEpOzJsansjgxgWTkRsIiopLek-I',
    appId: '1:567445844346:ios:a43e6d0348ad6d8685e6c3',
    messagingSenderId: '567445844346',
    projectId: 'quran-app-9116d',
    storageBucket: 'quran-app-9116d.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXGbIlEpOzJsansjgxgWTkRsIiopLek-I',
    appId: '1:567445844346:ios:a43e6d0348ad6d8685e6c3',
    messagingSenderId: '567445844346',
    projectId: 'quran-app-9116d',
    storageBucket: 'quran-app-9116d.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz5CqwBsf1SiyNKznui9bsdxp5RQ7L-LE',
    appId: '1:567445844346:web:880a36b55ff8308f85e6c3',
    messagingSenderId: '567445844346',
    projectId: 'quran-app-9116d',
    authDomain: 'quran-app-9116d.firebaseapp.com',
    storageBucket: 'quran-app-9116d.firebasestorage.app',
    measurementId: 'G-JRCG47ZFN5',
  );
}
